### ISSUE TITLE
develop topics

### ISSUE THREAD

**Issue by 00aixxia00** [00aixxia00/Lifehack-Engine#10]

**Comment by miriamin** [comment]
https://webis.de/downloads/lecturenotes/information-retrieval/unit-en-laboratory-experiments.pdf

**Comment by miriamin** [comment]
[shared document](https://docs.google.com/document/d/1JkW9mwSjbJvs08pNgrpcORaT7Cr5hG4rTvAQs7HMTyk/edit?usp=sharing)
