### ISSUE TITLE
Cross-Origin Request Blocked - Search fails

### ISSUE THREAD

**Issue by shahbazsyed** [00aixxia00/Lifehack-Engine#15]
Hi ,
When I start up the search engine and look for a query, the browser blocks cross-origin requests and the search does not return anything.

![image](https://user-images.githubusercontent.com/4356098/65240389-752eaa00-dae1-11e9-97a4-38d538464ae5.png)

Can you try setting this up in the virtual machine I provided in the Slack channel and test if it works?

**Comment by shahbazsyed** [comment]
@miriamin Any update regarding this ?

**Comment by 00aixxia00** [comment]
it should be working now

**Comment by shahbazsyed** [comment]
I am still getting the same error for this issue.

**Comment by 00aixxia00** [comment]
Yes, I tried it and it is working inside the VM.

**Comment by 00aixxia00** [comment]
![Screenshot from 2019-09-24 17-50-02](https://user-images.githubusercontent.com/28895375/65528260-515dd080-def4-11e9-967b-8d24e3cff69d.png)
![Screenshot from 2019-09-24 17-50-11](https://user-images.githubusercontent.com/28895375/65528267-54f15780-def4-11e9-996c-747af9849feb.png)
![Screenshot from 2019-09-24 17-50-28](https://user-images.githubusercontent.com/28895375/65528274-5884de80-def4-11e9-834f-64f909cbb748.png)

**Comment by 00aixxia00** [comment]
including the flask-cors package should have fixed the error..

**Comment by shahbazsyed** [comment]
Thanks! It works now.
